### ISSUE TITLE
HTTPRedirect not always DEFLATED

### ISSUE THREAD

**Issue by Jockel007** [simplesamlphp/saml2#102]
Hello!

https://github.com/simplesamlphp/saml2/commits/master/src/SAML2/HTTPRedirect.php

In function receive() always "gzinflate($message);" is executed. 

You can have a look here:
https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf
=> 3.4.4.1 DEFLATE Encoding

"SAML protocol messages can be encoded into a URL via the DEFLATE compression method (see
[RFC1951]). "

So a DEFALTE of the message is not a "must-have" for a HTTPRedirect.

I received a pure base64-encoded, NOT deflated SAMLRequest from a SP.
The SimpleSAMLphp-Idp throws the error message: 
"Exception: Error while inflating SAML message."

It would be nice, if SimpleSAMLphp can check, if the message is DEFLATED and inflate the massage only if necessary.

**Comment by thijskh** [comment]
What is the value of the `SAMLEncoding` parameter in that request?

**Comment by Jockel007** [comment]
The SP sends an AuthnRequest without an optional SAMLEncoding query param. And the AuthnRequest-SAML-Message is not compressed by DEFLATE, only it is encoded in base64 and URLEncoding.

**Comment by thijskh** [comment]
According to section 3.4.4:
> A query string parameter named `SAMLEncoding` is reserved to identify the encoding mechanism used.
> If this parameter is omitted, then the value is assumed to be `urn:oasis:names:tc:SAML:2.0:bindings:URL-Encoding:DEFLATE`.

I think what the library does is correct then, if `SAMLEncoding` is omitted, the message is assumed to be deflated and will be inflated.

I have never before seen an SP that sent an undeflated HTTP-Redirect message, so I don't think this is a widespread problem. Probably the particular SP is buggy and should be fixed.

**Comment by Jockel007** [comment]
Thanks for your knowledge! I didn't read section 3.4.4. I'm sorry for it and will close the issue.

Only FYI: https://issues.shibboleth.net/jira/browse/OSJ-190
