### ISSUE TITLE
"Which version to pick?" in README.md

### ISSUE THREAD

**Issue by timwienk** [simplesamlphp/saml2#109]
The text under `"Which version to pick?"` in README.md mentions that it is strongly recommended to use the latest stable version of the `2.x` range.

With the (relatively) recent release of the `3.x` range, I assume that this needs to be updated.

**Comment by thijskh** [comment]
Yes. I'll clean this up soon, on 6 Dec at the latest.

**Comment by thijskh** [comment]
Fixed in a0da1ed08f6998d20276e1a88a3fe8f6a398267c
