### ISSUE TITLE
metadata parsing fails (debian 9, php7)

### ISSUE THREAD

**Issue by enricocavalli** [simplesamlphp/saml2#112]
Today I noticed that simplesaml (branch master) was not able to parse metadata from edugain federation (http://www.garr.it/idem-metadata/edugain2idem-metadata-sha256.xml) on a preprod environment. After some debugging I noticed that parsing terminates with no errors on this line

https://github.com/simplesamlphp/saml2/blob/af52ace51808b6c107dfa0750a2be043b71073d1/src/SAML2/XML/md/Extensions.php#L55

For instance  with https://shib.manchester.ac.uk/shibboleth - this is a print of the node element that generates the failure

DOMElement Object
(
    [tagName] => mdrpi:RegistrationInfo
    [schemaTypeInfo] => 
    [nodeName] => mdrpi:RegistrationInfo
    [nodeValue] => 
		http://ukfederation.org.uk/doc/mdrps-20130902
	
    [nodeType] => 1
    [parentNode] => (object value omitted)
    [childNodes] => (object value omitted)
    [firstChild] => (object value omitted)
    [lastChild] => (object value omitted)
    [previousSibling] => (object value omitted)
    [nextSibling] => (object value omitted)
    [attributes] => (object value omitted)
    [ownerDocument] => (object value omitted)
    [namespaceURI] => urn:oasis:names:tc:SAML:metadata:rpi
    [prefix] => mdrpi
    [localName] => RegistrationInfo
    [baseURI] => /var/simplesamlphp/
    [textContent] => 
		http://ukfederation.org.uk/doc/mdrps-20130902
	
)

I get no error at all, so I have no useful clues. 

It does not seem a php memory limit issue.

Probably this is not a good way to report a bug,  and almost certainly I should stop messing with not released version of simplesaml...

**Comment by tvdijen** [comment]
How exactly are you parsing that file?
I've tried converting it using the metadata-converter and that either left me with a "HTTP/504 Gateway Timeout", or with no visible error in the browser (seems like nothing happened). PHP logs show that the POST-data exceeded the maximum default of 8MB though... It's just an insane large metadata-file...

**Comment by enricocavalli** [comment]
I started noticing that metarefresh from cron had expired metadata. So for debugging purposes I downloaded it and run metarefresh.php -s edugain2idem-metadata-sha256.xml

I was trying to identify the cause of "XML parser error when parsing http://www.garr.it/idem-metadata/edugain2idem-metadata-sha256.xml - attempting to re-use cached metadata" when run from the IDP manual metarefresh call.

Thank you.

**Comment by enricocavalli** [comment]
Sorry, I didn't specify that I  get the error on simplesamlphp branch master, composer dependencies up to date. On simplesaml 1.15 the same file does not generate any error.

**Comment by tvdijen** [comment]
Can you get me a copy of your `config/module_metarefresh.php`? Maybe I can do some debugging then, without having to find out how to configure that module first...

**Comment by thijskh** [comment]
I've heard a similar report here as well about eduGAIN metadata import failing on SSP master.

**Comment by enricocavalli** [comment]
[config-metarefresh.php.gz](https://github.com/simplesamlphp/saml2/files/1659151/config-metarefresh.php.gz)

here you are

**Comment by tvdijen** [comment]
Thanks Enrico, I'll get at it tonight..

**Comment by tvdijen** [comment]
@enricocavalli could you downgrade simplesamlphp/saml2 to 3.1.0 or even 3.0.3 and see what it does?
(i.e. set a specific version in `composer.json` and run `composer update`)
That would really help us narrow it down...

**Comment by enricocavalli** [comment]
simplesamlphp/saml2  3.1.0 seems to work

metarefrsh.php -s ... produces output 

cron works and metadata are correctly update

**Comment by tvdijen** [comment]
Thanks Enrico, that is really really helpful!!
I'm suspecting one of the 'strict type check' commits I've done for 3.1.1...

**Comment by tvdijen** [comment]
On second thought, I'm suspecting Jaime's last commit regarding timestamps:

`<mdrpi:RegistrationInfo registrationAuthority="http://ukfederation.org.uk" registrationInstant="**2007-10-15T11:05:25.614639Z**">`

**Comment by thijskh** [comment]
See my comments on that commit.

**Comment by tvdijen** [comment]
You should be fine again if you pull in the latest `master`, Enrico!

**Comment by enricocavalli** [comment]
yes, thank you !
