### ISSUE TITLE
PHP 7: Don't implement the "Throwable" interface directly

### ISSUE THREAD

**Issue by bkosborne** [simplesamlphp/saml2#113]
I ran a [static code analysis](https://github.com/wimg/PHPCompatibility/) on this codebase and it reported that many of the exceptions defined by this library implement PHP's [Throwable](http://php.net/manual/en/class.throwable.php) interface, but that this interface cannot (should not?) be implemented directly.

Not sure if it actually causes a fatal exception in PHP 7 or not, I'm just reporting what the analysis returned and what the docs say.

**Comment by jaimeperez** [comment]
Hi @bkosborne!

Unfortunately, it looks like that particular static analyzer does not properly implement namespace support. The SAML2 library does not implement PHP's `Throwable` interface directly. Where you see a `implements Throwable` statement on a class, you will always see either `use SAML2\Exception\Throwable;` or `namespace SAML2\Exception;` before that. That means the `Throwable` interface being implemented is `SAML2\Exception\Throwable`, not `\Throwable`.

**Comment by bkosborne** [comment]
Oh, wow, sorry I didn't check more closely. Thanks for the quick reply!

**Comment by jaimeperez** [comment]
No problem at all! On the contrary, thanks for reporting 😉
