### ISSUE TITLE
LogoutRequest Issuer missing NS

### ISSUE THREAD

**Issue by vivalton** [simplesamlphp/saml2#115]
What I see in the saml message:

`<saml:Issuer>.....</saml:Issuer>`

What I expect to see in the saml message: 

`<saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">.....</saml:Issuer>`

I'm running a SP and my logout requests are failing at my Idp probably because of the missing NS. At least that is what I am being told by them. Can someone help with this ?

**Comment by jaimeperez** [comment]
Hi @vivalton,

If the IdP is complaining about that, then they clearly have an issue. You don't need to declare namespaces for each element using them, as they are inherited by parent elements. The `saml` namespace they say is missing is declared at the parent `samlp:LogoutRequest` element, so there's no need to redeclare it.

Unless you can provide a LogoutRequest message showing that the namespace is actually not declared, this is not an issue in this library, but in the IdP you are talking to. Bear in mind that if this was an actual issue, single logout would be broken and we would have had reports about it.
