### ISSUE TITLE
PHP 7.2 - Cannot change session cookie parameters when session is active

### ISSUE THREAD

**Issue by TomHart** [simplesamlphp/saml2#116]
Line 350 of /lib/SimpleSAML/SessionHandlerPHP.php is causing notices to be raised in the log files [as of PHP 7.2](https://stackoverflow.com/questions/47700336/php-7-2-warning-cannot-change-session-name-when-session-is-active). Would it be possible to fix this so these are no longer raised?

**Comment by tvdijen** [comment]
Line 350 of what file are you talking about?

**Comment by TomHart** [comment]
Whoops, sorry! /lib/SimpleSAML/SessionHandlerPHP.php

**Comment by tvdijen** [comment]
So you’ve also managed to put the issue in the wrong repository :’)

**Comment by TomHart** [comment]
Damn, can you tell I don't use Github much :P? Shall I close/re-open in the other Repo, or can this be moved? Yeah that's the one I'm getting.

**Comment by tvdijen** [comment]
It cannot be moved, so if you would be so kind? :)
Would you also be able to move the `session_set_cookie_params()` below the if-statement and see if that solves your problem? https://github.com/tvdijen/simplesamlphp/commit/ec7d8a5bfe25157d995c7d1c0ee5f9686e83461b
