### ISSUE TITLE
Add method to get signature type to interface "SignedElement"

### ISSUE THREAD

**Issue by jbaron-gingco** [simplesamlphp/saml2#123]
When validating signatures, I am usually in the following situation:
 * I have a public key needed to validate the signature, as base64 encoded string.
 * I have the `SignedElement` (e.g. a message or a metadata document).
 * I want to validate the signature on the signed element.

In this case, I am facing the problem of finding out the signature algorithm. The `XMLSecurityKey` needs a type, which MUST match the type use to create the signature. However, there is no easy way of finding out that type, so I have to get that algorithm depending on the actual type of the element that I am validating.

This could be fixed by adding a method `getSignatureMethod` to the `SignedElement` interface.

**Comment by jaimeperez** [comment]
How are you using the SAML2 library? Can you give as a code example?

We are working on a replacement for xmlseclibs, which should allow us to handle use cases like yours easier than now.

**Comment by jbaron-gingco** [comment]
I am using the follwoing code to check the signature of an arbitrary `SignedElement`. The `$certificateString` is the X509 encoded certificate to use for the check, without the PEM wrapper (as it is transmitted in metadata documents):

    const X509_CERTIFICATE_WRAP = "-----BEGIN CERTIFICATE-----\n%s\n-----END CERTIFICATE-----";

    private function createKeyObjectFromPemCertificate($signatureAlgorithm, $certificateString)
    {
        $keyObject = new XMLSecurityKey($signatureAlgorithm, ['type' => 'public']);

        $pemCertificateString  = sprintf(self::X509_CERTIFICATE_WRAP, $certificateString);
        $keyObject->loadKey($pemCertificateString, false, true);

        return $keyObject;
    }

    public function isSignatureValid(SignedElement $signedElement, $certificateString)
    {
        if ($signedElement instanceof Message || $signedElement instanceof Assertion) {
            try {
                return $signedElement->validate(
                    $this->createKeyObjectFromPemCertificate($signedElement->getSignatureMethod(), $certificateString)
                );
            } catch (\Throwable $throwable) {
                $this->logger->debug('Signature verification failed', ['exception' => $throwable]);
                return false;
            }
        } elseif ($signedElement instanceof SignedElementHelper) {
            $certificatesThatSignedTheElement = $signedElement->getValidatingCertificates();

            return in_array($certificateString, $certificatesThatSignedTheElement, true);
        }

        throw new InvalidOperationException(
            'Cannot validate signatures for elements of type "' . get_class($signedElement) . '"'
        );
    }

I hope this code is understandable... I would very much appreciate a simpler way to do this, if you can tell me one.

**Comment by tvdijen** [comment]
I believe taht on `master` this has been resolved. Signed objects now have a Signature-property holding a ds:Signature, which in turn has a getAlgorithm-method.
