### ISSUE TITLE
SAML2\Compat\Ssp\Container::generateId() depends on SimpleSAML_Utilities which is not included as a dependency

### ISSUE THREAD

**Issue by desjob** [simplesamlphp/saml2#125]
Consider the following code:

**/composer.json**
```js
{
    "require": {
        "simplesamlphp/saml2": "~3.1.6"
    }
}
```

**/application.php**
```php
<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

new \SAML2\Assertion();
```

After running:
- composer install
- php application.php

you will get the following error:

> PHP Fatal error:  Uncaught Error: Class 'SimpleSAML_Utilities' not found in /var/www/farmed-saml-example/vendor/simplesamlphp/saml2/src/SAML2/Compat/Ssp/Container.php:36

It looks like the package simplesamlphp/saml2 has a dependency on simplesamlphp/simplesamlphp, however, this is not provided when requiring  simplesamlphp/saml2 through composer.

**Comment by thijskh** [comment]
I think this is answered by bullet 2 in "Usage": https://github.com/simplesamlphp/saml2#usage

**Comment by desjob** [comment]
why is it not included as a dependency in the require section of composer.json in simplesamlphp/saml2 ?
Now i will have to figure out/guess the version dependencies between saml2 and simplesamlphp myself instead of having composer take care of it.

**Comment by thijskh** [comment]
simplesamlphp/simplesamlphp is not a dependency per se, that's why it's not listed.

**Comment by desjob** [comment]
Sorry i removed my comment because i should read first :)

So basically simplesamlphp/simplesamlphp is only a dependency if you decide to use the provided `SAML2\Compat\Ssp\Container` ?

**Comment by thijskh** [comment]
Yes, you can implement your own container based on the example given.

**Comment by johnorourke** [comment]
If you instatiate any of the bindings eg. new \SAML2\HTTPRedirect, this sill use Compat\Ssp\Container and therefore create a dependency on SimpleSAML_Utilities
