### ISSUE TITLE
3.2.5 needs a tag

### ISSUE THREAD

**Issue by akinspe** [simplesamlphp/saml2#133]
Unfortunately 3.2.4 is broken due to 49c183010e1a15bddc38dc26f252026718306f1d

39ede7d2d1f5e33b0b55a27c75100ec69edf1171
and 
0e6632e8a208fa1f3ff3786d997f27c1d430de80

Have addressed some of those issues, but it would helpful to know when it will be tagged because some projects (i.e. simplesamlphp) will cause the most recent stable to be installed.

**Comment by thijskh** [comment]
Tagged, sorry for the hassle.
