### ISSUE TITLE
Please stop making incompatible changes in minor level versions

### ISSUE THREAD

**Issue by jbaron-gingco** [simplesamlphp/saml2#148]
Hi!

Recently, there were changes to the API that broke our application. One example is this one:

https://github.com/simplesamlphp/saml2/commit/94d61b2f5eeb7aa96784c87f9d58b8c7992fbc0f#diff-35f750cac20c45bceb545dd2e20dae85

The method `getWasSignedAtConstruction` was renamed to `wasSignedAtConstruction`.

I think it's a good idea to introduce changes like that, but please incate in your versioning that a new version contains backwards-incompatible changes. So versions after November 30. 2019 should have had major version 4.

Thanks for your work :-)

**Comment by tvdijen** [comment]
Hi @jbaron-gingco,

That's for reporting this.. This is obviiously not meant to happen and I will be reverting this one!
Are there any more BC changes that you are aware of?

**Comment by tvdijen** [comment]
It's done.. I will await your comment before I tag a new version

**Comment by jbaron-gingco** [comment]
I've not checked all changes in thé linked commit, only the first 2 or 3 pages - they do not seem to contain more backwards-incompatible changes.

**Comment by jbaron-gingco** [comment]
Thanks for the (really) fast reaction :-)

**Comment by tvdijen** [comment]
Phew :) Thanks, I will tag a new release right now.. 4000 lines is much to go over, so again we did not mean to break anything

**Comment by tvdijen** [comment]
Tagged v3.3.4 resolving this issue

**Comment by MKodde** [comment]
In v3.3.7 there is a [BC breaking](https://github.com/simplesamlphp/saml2/blob/release-3.x/src/SAML2/XML/md/RoleDescriptor.php#L300) leftover.

I'm not 100% sure how your backport workflow looks like. Can I open a PR to the `release-3.x` branch in order to fix this @tvdijen?

**Comment by tvdijen** [comment]
@MKodde Thanks for pointing this out. A new release has been tagged

**Comment by MKodde** [comment]
You're most welcome. And thank you for resolving this so quickly.

:rocket:
