### ISSUE TITLE
Proposal to add an UPGRADING.md

### ISSUE THREAD

**Issue by MKodde** [simplesamlphp/saml2#164]
In some of the projects I work at, we keep an UPGRADING.md file. We warn/inform users that are about to update to a new version about what they can expect when performing the upgrade.

Is this something we want to have in the saml2 library? I think it would be a nice addition to assist people in the upcoming 4.0 release. 

Do we also want this in the SimpleSAMLphp project? And include this in the contribution guidelines?

**Comment by thijskh** [comment]
Great idea. Done!
