### ISSUE TITLE
Add support for AES-GCM

### ISSUE THREAD

**Issue by Skywalker-11** [simplesamlphp/saml2#179]
simplsamlphp currently does not support AES in GCM mode.

If an IDP uses AES-GCM for encryption of the ssertions eg:
```
<saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
  ....
  <xenc:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#aes128-gcm" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"/> 
   ....
```
this creates an error in form of the following message on a SP running simplesamlphp:

```
simplesamlphp: 3  Decryption failed: Could not locate key algorithm in encrypted data.
simplesamlphp: 3  SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
simplesamlphp: 3  Backtrace:
simplesamlphp: 3  1 /opt/simplesamlphp/www/_include.php:17 (SimpleSAML_exception_handler)
simplesamlphp: 3  0  (N/A)
simplesamlphp: 3  Caused by: Exception: Failed to decrypt XML element.
simplesamlphp: 3  Backtrace:
simplesamlphp: 3  7 /opt/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:575 (SAML2\Utils::decryptElement)
simplesamlphp: 3  6 /opt/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/EncryptedAssertion.php:98 (SAML2\EncryptedAssertion::getAssertion)
simplesamlphp: 3  5 /opt/simplesamlphp/modules/saml/lib/Message.php:391 (SimpleSAML\Module\saml\Message::decryptAssertion)
simplesamlphp: 3  4 /opt/simplesamlphp/modules/saml/lib/Message.php:647 (SimpleSAML\Module\saml\Message::processAssertion)
simplesamlphp: 3  3 /opt/simplesamlphp/modules/saml/lib/Message.php:614 (SimpleSAML\Module\saml\Message::processResponse)
simplesamlphp: 3  2 /opt/simplesamlphp/modules/saml/www/sp/saml2-acs.php:134 (require)
simplesamlphp: 3  1 /opt/simplesamlphp/lib/SimpleSAML/Module.php:236 (SimpleSAML\Module::process)
simplesamlphp: 3  0 /opt/simplesamlphp/www/module.php:9 (N/A)
```

Depending on change in library xmlseclibs (https://github.com/robrichards/xmlseclibs/issues/134)

**Comment by blai-cartera** [comment]
@Skywalker-11 have you found any alternatives to simplesamlphp or a way to include 3rd party support of aes-gcm for simplesamlphp users?

**Comment by Skywalker-11** [comment]
I am not using simplesaml myself but noticed the error when interacting with 3rd party SPs

**Comment by melanger** [comment]
AES-GCM is the default in Shibboleth 4.0, so missing support breaks compatibility of SimpleSAMLphp with a growing number of SPs.

**Comment by tvdijen** [comment]
@melanger The issue here is not SimpleSAMLphp, but two dependency-levels down in the xmlseclibs library..  So, unless you can open up a can of crypto-savvy PHP developers, this is really out of our control.

**Comment by melanger** [comment]
@tvdijen There is an open issue in the library as well, https://github.com/robrichards/xmlseclibs/issues/134, but it seems that the support was actually added in 3.1 https://github.com/robrichards/xmlseclibs/releases/tag/3.1.0

**Comment by melanger** [comment]
Requires PHP 7.1+, but SimpleSAML already requires 7.2+ on master

**Comment by jaimeperez** [comment]
I might be mistaken here, but I would say this is just a matter of updating the xmlseclibs dependency, since 3.1.0 implements support for AES-GCM.

**Comment by IlariExove** [comment]
I see Shibboleth 4.0 IdPs using `http://www.w3.org/2009/xmlenc11#aes128-gcm` algorithm for encryption. This is a rising concern as 4.0 went GA in March. IdPs are rolling out v4 to production soon.

**Comment by tvdijen** [comment]
If you're using SimpleSAMLphp:
- On 1.18 you can get this working by running 'composer require robrichards/xmlseclibs:v3.1.0'.
- 1.19 will officially include this.

If you're using this library directly:
- Use v4.1.8 of the libary

**Comment by s0rin** [comment]
The workaround in SSP 1.18.7 to install manually xmlseclibs 3.1.0 over the existent 3.0.8 didn't work for me, the error "Failed to decrypt XML element" still occur. How to check the xmlseclibs installed version?

**Comment by tvdijen** [comment]
You can check the installed version in the composer.lock file

**Comment by s0rin** [comment]
The PHP version is right:
```
# php -v
PHP 7.2.33 (cli) (built: Sep  1 2020 05:35:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.33, Copyright (c) 1999-2018, by Zend Technologies
```
but the xmlseclibs is not:
```
# cat /var/simplesamlphp/composer.lock | grep xmlseclibs
                "robrichards/xmlseclibs": "^3.0.4",
```
Note. With the newer SSP 1.18.8 is no change :-(

In conclusion the workaround for 1.18.x to install xmlseclibs with composer manually is not working (maybe some steps are missing, i.e. to edit _composer.lock_?). I will rather wait for 1.19...

**Comment by tvdijen** [comment]
1.18.8 has the right one;
https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.18/composer.lock#L419

So it must be something else...

**Comment by s0rin** [comment]
and here? https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.18/composer.lock#L509

**Comment by tvdijen** [comment]
That one's not relevant.. The one I tagged is the one actually installed...
I'll see if I can run a few tests with aes-gcm encrypted assertions this weekend. and see if I can figure this out..
Reopening this so I won't forget

**Comment by s0rin** [comment]
I've retested 1.18.8 today and AES-GCM is still not working :-(

**Comment by tvdijen** [comment]
That doesn't surprise me, because nothing has changed in SimpleSAMLphp or the saml2 library..
I just need to find the time to work out a test-setup with AES-GCM encrypted assertions so I can reproduce your issue and see what changes we may need to get this working..

**Comment by tvdijen** [comment]
Well, the good news is that I can reproduce the issue, but the bad news is that I have no idea how to solve this...

First, there is this bug in xmlseclibs that needs to be taken care of;  https://github.com/robrichards/xmlseclibs/pull/213
Then, I found a bug in saml2 that I fixed:  https://github.com/simplesamlphp/saml2/blob/release-4.x/src/SAML2/EncryptedAssertion.php#L86-L88
I then ended up with an algorithm mismatch due to some hardcoded stuff in SSP, which for the test I manually changed to AES-GCM-128:  https://github.com/simplesamlphp/simplesamlphp/blob/e4246a2a0286e553f7544e20f0fd246aeea3d5df/modules/saml/lib/Message.php#L336

After the above I ended up with the following traceback:

```
Caused by: Exception: Failure decrypting Data (openssl symmetric) - error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length
Backtrace:
11 /apps/installation/simplesamlphp/simplesamlphp-1.19/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php:472 (RobRichards\XMLSecLibs\XMLSecurityKey::decryptSymmetric)
10 /apps/installation/simplesamlphp/simplesamlphp-1.19/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php:612 (RobRichards\XMLSecLibs\XMLSecurityKey::decryptData)
 9 /apps/installation/simplesamlphp/simplesamlphp-1.19/vendor/robrichards/xmlseclibs/src/XMLSecEnc.php:263 (RobRichards\XMLSecLibs\XMLSecEnc::decryptNode)
 8 /apps/installation/simplesamlphp/simplesamlphp-1.19/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:463 (SAML2\Utils::doDecryptElement)
 7 /apps/installation/simplesamlphp/simplesamlphp-1.19/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:498 (SAML2\Utils::decryptElement)
 6 /apps/installation/simplesamlphp/simplesamlphp-1.19/vendor/simplesamlphp/saml2/src/SAML2/EncryptedAssertion.php:122 (SAML2\EncryptedAssertion::getAssertion)
 5 /apps/installation/simplesamlphp/simplesamlphp-1.19/modules/saml/lib/Message.php:413 (SimpleSAML\Module\saml\Message::decryptAssertion)
 4 /apps/installation/simplesamlphp/simplesamlphp-1.19/modules/saml/lib/Message.php:674 (SimpleSAML\Module\saml\Message::processAssertion)
 3 /apps/installation/simplesamlphp/simplesamlphp-1.19/modules/saml/lib/Message.php:642 (SimpleSAML\Module\saml\Message::processResponse)
 2 /apps/installation/simplesamlphp/simplesamlphp-1.19/modules/saml/www/sp/saml2-acs.php:145 (require)
 1 /apps/installation/simplesamlphp/simplesamlphp-1.19/lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
 0 /apps/installation/simplesamlphp/simplesamlphp-1.19/www/module.php:10 (N/A)
```

**Comment by tvdijen** [comment]
OK, I got it working now.. I got off on the wrong foot last night a bit..

You need: robrichards/xmlseclibs#213 and 1f0c32f
And then in SimpleSAMLphp set https://github.com/simplesamlphp/simplesamlphp/blob/e4246a2a0286e553f7544e20f0fd246aeea3d5df/modules/saml/lib/Message.php#L312 to the right algo and you're all set!

I don't think it makes much sense to tag a new saml2-release until xmlseclibs is fixed, so I'm keeping this open and in the meanwhile I can try and work making the algorithm configurable in SSP.

**Comment by s0rin** [comment]
Retesting with 1.19-rc1 but still not working.

```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: Failed to decrypt XML element.
Backtrace:
7 vendor/simplesamlphp/saml2/src/SAML2/Utils.php:537 (SAML2\Utils::decryptElement)
6 vendor/simplesamlphp/saml2/src/SAML2/EncryptedAssertion.php:119 (SAML2\EncryptedAssertion::getAssertion)
5 modules/saml/lib/Message.php:413 (SimpleSAML\Module\saml\Message::decryptAssertion)
4 modules/saml/lib/Message.php:674 (SimpleSAML\Module\saml\Message::processAssertion)
3 modules/saml/lib/Message.php:642 (SimpleSAML\Module\saml\Message::processResponse)
2 modules/saml/www/sp/saml2-acs.php:145 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)
```

**Comment by tvdijen** [comment]
Maybe because 1.19-rc1 is ten days old and I got it working only 9 days ago?

**Comment by back-2-95** [comment]
Seems that  robrichards/xmlseclibs 3.1.1 includes the needed change:
https://github.com/robrichards/xmlseclibs/compare/3.1.0...3.1.1

SimpleSAMLphp still needs the https://github.com/simplesamlphp/simplesamlphp/blob/e4246a2a0286e553f7544e20f0fd246aeea3d5df/modules/saml/lib/Message.php#L312 change.

**Comment by tvdijen** [comment]
There's one PR that will land in 1.19;  https://github.com/simplesamlphp/simplesamlphp/pull/1377

**Comment by back-2-95** [comment]
I just got word from my university contact handling the Shibboleth 4:

Changing encryption from GCM (default in Shibboleth 4) to CBC made it work with both:
- SSP 1.18.6 (we had this before Shibboleth was updated)
- SSP 1.18.8 (works also with GCM)

**Comment by JanOppolzer** [comment]
I can confirm that SimpleSAMLphp 1.18.8 with updated `xmlseclibs` to 3.1.1 and updates to `EncryptedAssertion.php` and `Message.php` according to https://github.com/simplesamlphp/saml2/issues/179#issuecomment-687597903 makes it working with an Shibboleth IdP 4.0.1 using AES-GCM encryption.

Looking forward to see AES-GCM support in 1.19 out of the box.

**Comment by tvdijen** [comment]
Thanks @JanOppolzer ! There's some discussion on the changes to SSP 1.19, but the next RC should easy all of your problems.
