### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by chrisemerson** [simplesamlphp/saml2#186]
Is there anywhere I can see a changelog for older versions? Since you don't follow semantic versioning (an assumption based on the fact your upgrading file lists a BC breaking change between 4.0 and 4.1) and I can't see a changelog anywhere, I'm not sure what's going to happen when I upgrade 3.2 -> 3.4.2, which I need to do. Can you advise what changed in these versions, or what I should look out for?

**Comment by thijskh** [comment]
Thanks for the feedback. We do conform to semver and have now made that explicit in the readme file. We have started to use an UPGADING.md file which will be listing the breaking changes that you need to reckon with. For upgrades from pre-4.0 you can check the releases page where every release that has significant changes has these documented there.

(There will always be edge cases; the break in 4.1 is a carefully considered exception where the previous situation was also broken.)
