### ISSUE TITLE
Something is wrong but returning a 0 exit status

### ISSUE THREAD

**Issue by StephanMeijer** [simplesamlphp/saml2#196]
https://github.com/simplesamlphp/saml2/blob/2ca721f80278315afd40d045e7fd1be4f32a3c87/src/SAML2/SOAP.php#L88-L89

If something is going wrong, we might neet to return a non-zero exit status.

**Comment by thijskh** [comment]
I agree that the exit(0) is unlikely to be correct, but it makes no sense to me to use exit at all in a library. Much better to throw an exception there.
