### ISSUE TITLE
This package really needs some documentation

### ISSUE THREAD

**Issue by khan-zia** [simplesamlphp/saml2#238]
Let me set things straight, I agree to the argument that you really need to know your way around SAML2 before you can use this library. But, no matter how well you know SAML2, (Like I know it pretty blooming well), it doesn't mean that you can start using this package right away without having to figure out the bits and pieces.

I have spent a few hours now and I still don't know all that I need to. I have gone through over half of the code base and it seems that I need to go through all of it if I need to understand it all. THIS IS TRULY UNNECESSARY every time a developer or a team needs to use this package for the first time.

Could Someone please right just a couple of pages of documentation and save many hours and LOTS OF FRUSTRATION to every new adopter of this library. It will be hugely appreciated.

Thanks!

**Comment by tvdijen** [comment]
Thanks! We're working on a complete rewrite at the moment and some documentation should be part of that project's outcome.
Meanwhile, do you have any questions I can help you with?

**Comment by khan-zia** [comment]
Thank you @tvdijen , No issues at the moment. It's just taking some time to figure stuff out. I am testing with AWS SSO and I will definitely share if anything is worth sharing. We are hopefully going to build a huge SAML idp and add it to our existing OAuth based services. (perhaps an Okta competitor with much better, quantum proof security). I would love to contribute after my experience with this.
