### ISSUE TITLE
SimpleSAML Utils claaes referred in Container do not exist

### ISSUE THREAD

**Issue by voserwin** [simplesamlphp/saml2#264]
saml2\src\SAML2\Compat\SSp\Container.php is using:
```php
use SimpleSAML\Utils\HTTP;
use SimpleSAML\Utils\Random;
use SimpleSAML\Utils\System;
use SimpleSAML\Utils\XML;
```

But these classes do not exist.
I know where they are in in simpleSAMLphp\lib\SimpleSAML\Utils.
But this Container is not working now in the SAML2-only solution.

**Comment by tvdijen** [comment]
That's right.. You have to inject your own container and implement a few methods if you don't want to add a dependency on simplesamlphp.

**Comment by voserwin** [comment]
ok,so SimpleSAML\SAML2\Compat\Ssp\Container.php should be seen as an example?
but it is a non working example than, referring to namespaces that do not exist.

**Comment by tvdijen** [comment]
Those Compat-classes were just recently moved to SimpleSAMLphp because that is where they belong.  I can see how this is confusing.  It is indeed an example, so create your own implementation of the AbstractContainer and inject it when using this library.

**Comment by voserwin** [comment]
ok thanks for quick response.

**Comment by tvdijen** [comment]
No problem! Let me know if you have any more questions!
