### ISSUE TITLE
5.0.0-alpha.7: Response::toXML broken

### ISSUE THREAD

**Issue by SiebelsTim** [simplesamlphp/saml2#300]
Somewhere between alpha.4 and alpha.7 the entire `toXML`-infrastructure was reworked. Now `Response::toXML` is broken.

* `Response::toXML` was removed in favor of `toUnsignedXML` where `AbstractMessage::toXML` calls `$this->toUnsignedXML` 
* `Response extends AbstractStatusResponse`. `AbstractStatusResponse uses ExtensionsTrait`.
* `ExtensionsTrait` overwrites `AbstractStatusResponse::toXML` which does *not* invoke `toUnsignedXML` rendering the XML-conversion incomplete

As a result, a `Response` will always be `<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"/>` missing all its children and various attributes.

**Comment by tvdijen** [comment]
Hi Tim!  Thanks for reporting this.  The 5.0 release is still a work in progress, but this was indeed a bug.. The trait was completely unnecessary, so I simply removed it.
