### ISSUE TITLE
Migrate to PSR-2?

### ISSUE THREAD

**Issue by cb8** [simplesamlphp/saml2#31]
As the first PHP version which supported namespacing is already EOL, I think it's time to move on and use proper namespaces (like *SAML2\Assertion\Processor* instead of *SAML2_Assertion_Processor*).

If desired, I can supply a pull-request.

**Comment by relaxnow** [comment]
I think after even Rob upgraded xmlseclibs to use PSR-2 we should do the same, all that remains is for someone to actually do it... :smile:

**Comment by DRvanR** [comment]
Actually still have a WiP branch that is like 80% done.... Will update and finish it, not sure if I can do that this week, but should be able to within a week or two.

**Comment by jaimeperez** [comment]
Thanks guys for moving this forward, I completely support you too :smile: 

*xmlseclibs* has already a branch (actually, master) implementing namespaces. I don't know if it's fully PSR-2 compliant, but my plan is to migrate to it right away. I can do the same with the SAML2 library as soon as it is ready. Meanwhile, some new classes in SimpleSAMLphp are using namespaces directly.

Regarding the autoloader, you are right. Theoretically, I think it could be possible to *rename* a class in the autoloader, basically by defining the class you are looking for (the one with underscores) dynamically, based on the class defined with namespaces. However, I haven't tried this myself and that solution would be an overkill IMHO. We could also keep the old classes as wrappers for the renamed ones, but that would also be a huge work.

So if we can move the entire library to PSR-2, including namespaces, I commit myself to update all the code needed in SimpleSAMLphp to use the new classes.

**Comment by DRvanR** [comment]
Resolved through #53 and #57
