### ISSUE TITLE
$document->documentElement is NULL

### ISSUE THREAD

**Issue by Khurram664** [simplesamlphp/saml2#329]
I am using PHP 8 and I have installed simplesamlphp 2.0.0 on the server. I have checked the version of saml2 which is 4.6.5. I am seeing an error related to DOMText. But the root cause of the error is below:

In src/SAML2/HTTPPOST.php :

`$document = DOMDocumentFactory::fromString($msgStr);`
`Utils::getContainer()->debugMessage($document->documentElement, 'in');`
`if (!$document->firstChild instanceof \DOMElement) {
       throw new \Exception('Malformed SAML message received.');
}`
`$msg = Message::fromXML($document->firstChild);`

It fails to make $document->documentElement as it is coming out as NULL. Although I can see $document is a DOM type and contains the SAML related information . the subsequent function calls  Utils::getContainer()->debugMessage And Message::fromXML($document->firstChild); both are getting failed. My question is is this related to version of libxml or some other extension? Or some encoding issue. I have verified that XML response from SAML is coming through and having a valid response. 
I can also provide the whole stack trace of the Error. Thanks.

**Comment by thijskh** [comment]
A full stack trace is appreciated together with the XML that triggers this (or even better a SAML Trace with the [SAML Tracer](https://addons.mozilla.org/nl/firefox/addon/saml-tracer/)

**Comment by Khurram664** [comment]
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] SimpleSAML\Error\Exception: Warning - Undefined property: DOMText::$wholeText at /var/simplesamlphp/src/SimpleSAML/Utils/XML.php:170
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] Backtrace:
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 17 /var/simplesamlphp/public/_include.php:86 (SimpleSAML_error_handler)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 16 /var/simplesamlphp/src/SimpleSAML/Utils/XML.php:170 (SimpleSAML\Utils\XML::formatDOMElement)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 15 /var/simplesamlphp/src/SimpleSAML/Utils/XML.php:220 (SimpleSAML\Utils\XML::formatDOMElement)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 14 /var/simplesamlphp/src/SimpleSAML/Utils/XML.php:253 (SimpleSAML\Utils\XML::formatXMLString)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 13 /var/simplesamlphp/src/SimpleSAML/Utils/XML.php:137 (SimpleSAML\Utils\XML::debugSAMLMessage)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 12 /var/simplesamlphp/src/SimpleSAML/Compat/SspContainer.php:54 (SimpleSAML\Compat\SspContainer::debugMessage)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 11 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/HTTPRedirect.php:42 (SAML2\HTTPRedirect::getRedirectURL)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 10 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/HTTPRedirect.php:88 (SAML2\HTTPRedirect::send)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 9 /var/simplesamlphp/modules/saml/src/Auth/Source/SP.php:657 (SimpleSAML\Module\saml\Auth\Source\SP::sendSAML2AuthnRequest)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 8 /var/simplesamlphp/modules/saml/src/Auth/Source/SP.php:641 (SimpleSAML\Module\saml\Auth\Source\SP::startSSO2)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 7 /var/simplesamlphp/modules/saml/src/Auth/Source/SP.php:690 (SimpleSAML\Module\saml\Auth\Source\SP::startSSO)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 6 /var/simplesamlphp/modules/saml/src/Auth/Source/SP.php:779 (SimpleSAML\Module\saml\Auth\Source\SP::authenticate)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 5 /var/simplesamlphp/src/SimpleSAML/Auth/Source.php:195 (SimpleSAML\Auth\Source::initLogin)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 4 /var/simplesamlphp/src/SimpleSAML/Auth/Simple.php:167 (SimpleSAML\Auth\Simple::login)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 3 [builtin] (call_user_func_array)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 2 /var/simplesamlphp/src/SimpleSAML/HTTP/RunnableResponse.php:72 (SimpleSAML\HTTP\RunnableResponse::sendContent)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 1 /var/simplesamlphp/vendor/symfony/http-foundation/Response.php:394 (Symfony\Component\HttpFoundation\Response::send)
Mar 16 08:32:52 usawodlbclapp03 simplesamlphp[3690490]: 3 [26a3491dc4] 0 /var/simplesamlphp/public/module.php:14 (N/A)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] SimpleSAML\Error\Exception: Warning - Undefined property: DOMDocument::$documentElement at /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/HTTPPost.php:110
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] Backtrace:
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 7 /var/simplesamlphp/public/_include.php:86 (SimpleSAML_error_handler)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 6 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/HTTPPost.php:110 (SAML2\HTTPPost::receive)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 5 /var/simplesamlphp/modules/saml/src/Controller/ServiceProvider.php:209 (SimpleSAML\Module\saml\Controller\ServiceProvider::assertionConsumerService)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 4 /var/simplesamlphp/vendor/symfony/http-kernel/HttpKernel.php:163 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 3 /var/simplesamlphp/vendor/symfony/http-kernel/HttpKernel.php:75 (Symfony\Component\HttpKernel\HttpKernel::handle)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 2 /var/simplesamlphp/vendor/symfony/http-kernel/Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 1 /var/simplesamlphp/src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 0 /var/simplesamlphp/public/module.php:14 (N/A)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] Backtrace:
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 2 /var/simplesamlphp/public/_include.php:28 (SimpleSAML_exception_handler)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 1 /var/simplesamlphp/vendor/symfony/error-handler/ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 0 [builtin] (N/A)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] Caused by: InvalidArgumentException: Invalid input parameters.
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] Backtrace:
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 8 /var/simplesamlphp/src/SimpleSAML/Utils/XML.php:100 (SimpleSAML\Utils\XML::debugSAMLMessage)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 7 /var/simplesamlphp/src/SimpleSAML/Compat/SspContainer.php:54 (SimpleSAML\Compat\SspContainer::debugMessage)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 6 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/HTTPPost.php:110 (SAML2\HTTPPost::receive)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 5 /var/simplesamlphp/modules/saml/src/Controller/ServiceProvider.php:209 (SimpleSAML\Module\saml\Controller\ServiceProvider::assertionConsumerService)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 4 /var/simplesamlphp/vendor/symfony/http-kernel/HttpKernel.php:163 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 3 /var/simplesamlphp/vendor/symfony/http-kernel/HttpKernel.php:75 (Symfony\Component\HttpKernel\HttpKernel::handle)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 2 /var/simplesamlphp/vendor/symfony/http-kernel/Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 1 /var/simplesamlphp/src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] 0 /var/simplesamlphp/public/module.php:14 (N/A)
Mar 16 08:32:55 usawodlbclapp03 simplesamlphp[3709159]: 3 [26a3491dc4] Error report with id 106682b9 generated.

**Comment by tvdijen** [comment]
`Undefined property: DOMText::$wholeText at /var/simplesamlphp/src/SimpleSAML/Utils/XML.php:170`

This means your PHP installation is broken

**Comment by Khurram664** [comment]
Ok Here is the XML response though:


<samlp:response id="_089130d8-c3d4-42b7-a1dc-ed4571bd9b92" version="2.0" issueinstant="2023-03-16T13:30:37.030Z" destination="TESTSERVER/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp" inresponseto="_01cdd646adba8c95cb625515c620d61d27e809f01f"
	xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
	<issuer
		xmlns="urn:oasis:names:tc:SAML:2.0:assertion">IDPID
	</issuer>
	<samlp:status>
		<samlp:statuscode value="urn:oasis:names:tc:SAML:2.0:status:Success"></samlp:statuscode>
	</samlp:status>
	<assertion id="_71d35e35-d84b-4a7f-a9b5-fc121e2e3d00" issueinstant="2023-03-16T13:30:36.853Z" version="2.0"
		xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
		<issuer>IDPID</issuer>
		<signature
			xmlns="http://www.w3.org/2000/09/xmldsig#">
			<signedinfo>
				<canonicalizationmethod algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
					<signaturemethod algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256">
						<reference uri="#_71d35e35-d84b-4a7f-a9b5-fc121e2e3d00">
							<transforms>
								<transform algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature">
									<transform algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></transform>
								</transform>
							</transforms>
							<digestmethod algorithm="http://www.w3.org/2001/04/xmlenc#sha256">
								<digestvalue>NV6YyS1PeCCe1KmLg+5uUpv9uXLiit/PNsbKMNYoopE=</digestvalue>
							</digestmethod>
						</reference>
					</signaturemethod>
				</canonicalizationmethod>
			</signedinfo>
			<signaturevalue>EP6kYqv4RpjRb6tjXB00yoZJ/kmoaEdpUzeI06YBYt0nJp1sWqu1GeKy5VvPLoDO0HWHyQ0RD1+HQtIHGnimZG3Q6E+MCw7v9EV7hBT5MT+85ifjDOfD4m9HlzDB32J/8hSAHTfLceHQ6/e29i3qjzTTJjcluZPwL3tA3q2Q5MAjQ0lrLgODp0p+Ao3DmIR2tUgTlQ3/Dr20QOrtHeZO6E7kV9qGIsepi98IgcMh2H6tbymm1yPVp1BTfnlqHvQkEoaSODvbGKNUqPxzvjVGY6BnIO1NSe3qL0uJQXzS3WfM+BMo+rFmExf+hZJW5gvm3P7j+HEvffq8maQ8AFljHA==</signaturevalue>
			<keyinfo>
				<x509data>
					<x509certificate>IDPCERT</x509certificate>
				</x509data>
			</keyinfo>
		</signature>
		<subject>
			<nameid format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">cQkLN4sv3zQBrLr1574CmCGvkjAHod5M4WTJkJysU48=</nameid>
			<subjectconfirmation method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
				<subjectconfirmationdata inresponseto="_01cdd646adba8c95cb625515c620d61d27e809f01f" notonorafter="2023-03-16T14:30:36.160Z" recipient="TESTSERVER/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp"></subjectconfirmationdata>
			</subjectconfirmation>
		</subject>
		<conditions notbefore="2023-03-16T13:25:36.160Z" notonorafter="2023-03-16T14:30:36.160Z">
			<audiencerestriction>
				<audience>TESTSERVER/simplesaml/module.php/saml/sp/metadata.php/default-sp</audience>
			</audiencerestriction>
		</conditions>
		<attributestatement>
			<attribute name="http://schemas.microsoft.com/identity/claims/tenantid">
				<attributevalue>76we624f-e27a-4b03-8702-L6fpa389e009</attributevalue>
			</attribute>
			<attribute name="http://schemas.microsoft.com/identity/claims/objectidentifier">
				<attributevalue>80we624f-e33a-4c03-8702-L6olk389e009</attributevalue>
			</attribute>
			<attribute name="http://schemas.microsoft.com/identity/claims/identityprovider">
				<attributevalue>IDPID</attributevalue>
			</attribute>
			<attribute name="http://schemas.microsoft.com/claims/authnmethodsreferences">
				<attributevalue>http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/password</attributevalue>
				<attributevalue>http://schemas.microsoft.com/claims/multipleauthn</attributevalue>
			</attribute>
			<attribute name="Email">
				<attributevalue>kbangash@test.com</attributevalue>
			</attribute>
			<attribute name="First Name">
				<attributevalue>Khurram</attributevalue>
			</attribute>
			<attribute name="Brand">
				<attributevalue>TESTCompany</attributevalue>
			</attribute>
			<attribute name="Last Name">
				<attributevalue>Bangash</attributevalue>
			</attribute>
			<attribute name="Country">
				<attributevalue>US</attributevalue>
			</attribute>
			<attribute name="Employee ID">
				<attributevalue>000000007</attributevalue>
			</attribute>
		</attributestatement>
		<authnstatement authninstant="2023-03-16T12:22:59.273Z" sessionindex="_71d35e35-d84b-4a7f-a9b5-fc121e2e3d00">
			<authncontext>
				<authncontextclassref>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</authncontextclassref>
			</authncontext>
		</authnstatement>
	</assertion>
</samlp:response>

**Comment by Khurram664** [comment]
I have pasted the XML response above.
@tvdijen Hi Tim. I will meanwhile check the php --ini thing.

**Comment by Khurram664** [comment]
A common cause for this error is that the dom-extension is being loaded twice

That exactly was the issue. Thanks @tvdijen  you were of great help. Closing this issue and hoping it will help someone one day.

**Comment by thijskh** [comment]
Why is that possible and does it not create an explicit error?

**Comment by Khurram664** [comment]
I am myself not sure, actually the platform is Red Hat 8 maybe permission issues . I am not sure.

**Comment by tvdijen** [comment]
Ah, makes sense!  When you upgrade PHP you will not get the new config templates, but instead the new templates are installed as .conf.dist files. So basically you have been running PHP 8 with PHP 7.4 configuration. I can recommend using the [REMI](https://rpms.remirepo.net/enterprise/8/)-repository for PHP. It will allow you to run multiple versions of PHP simultaneously, and their configs will be completely isolated. The author of the repo is a Red Hat employee, so it's not a sketchy repo.
