### ISSUE TITLE
Customizable NameID-format

### ISSUE THREAD

**Issue by jellingsen** [simplesamlphp/saml2#330]
The NameID format is hard-coded inside [Constants](https://github.com/simplesamlphp/saml2/blob/master/src/SAML2/Constants.php#L197). 

We have a case now where that value has to be `NAMEID_PERSISTENT`

**Comment by tvdijen** [comment]
I think you're reading your requirement wrong. `NAMEID_PERSISTENT` as a value would not even be a valid URI/URN as the specifications mandate.

**Comment by jellingsen** [comment]
Never post issues before the first cup of coffee!

You are ofcourse correct. I read my notes wrong.

[This](https://github.com/flipboxfactory/saml-core/blob/master/src/services/messages/LogoutRequest.php#L83) is where i would need to use `NAMEID_PERSISTENT`. This is a Auth0-implementation. I've edited the vendor-files for now and made it work.
