### ISSUE TITLE
Config getCertPath is not static anymore

### ISSUE THREAD

**Issue by marienpflaum** [simplesamlphp/saml2#332]
Hi,

We are upgrading to simplesamlphp/simplesamlphp v2. It seems that the getCertPath method called here:

https://github.com/simplesamlphp/saml2/blob/74acb4865ad5a08adf02dd965237e552f479a9bc/src/SAML2/SOAPClient.php#L73

is not longer static, and the Config class should be intiantiated. Is the saml2 package compatibel with the new simplesamlphp/simplesamlphp version?

Kind regard!

**Comment by tvdijen** [comment]
Good catch! We obviously missed a spot there. Will fix!

**Comment by tvdijen** [comment]
Fixed in v4.6.7 - will be included in the next SSP v2.0.4 (release date TBD)
