### ISSUE TITLE
Error: Typed static property SimpleSAML\SAML2\Compat\ContainerSingleton::$container must not be accessed before initialization

### ISSUE THREAD

**Issue by meschenbaum** [simplesamlphp/saml2#334]
Getting Type error on latest v5.0.0-alpha.4 branch.

_Error: Typed static property SimpleSAML\SAML2\Compat\ContainerSingleton::$container must not be accessed before initialization in SimpleSAML\SAML2\Compat\ContainerSingleton::getInstance() (line 22 of /code/vendor/simplesamlphp/saml2/src/SAML2/Compat/ContainerSingleton.php)._

**Comment by tvdijen** [comment]
How is this a TypeError? And do you get the same error with 4.6.8?
Because I'm pretty sure nothing changed to the container-class in between versions..
