### ISSUE TITLE
simplesamlphp/simplesamlphp problem with simplesamlphp/saml2

### ISSUE THREAD

**Issue by tadasrimkus** [simplesamlphp/saml2#344]
`simplesamlphp/simplesamlphp: dev-master#8c6ee7dd6a6` requires `simplesamlphp/saml2: ^5.0.0-alpha.1` - currently alpha.8 is available, which has a problem with `ContainerSingleton::getInstance()` change (i.e. 
v4.6.8 still had it https://github.com/tadasrimkus/saml2/blob/v4.6.8/src/SAML2/Compat/ContainerSingleton.php). 

Please see the link to the issue below to get more information about the problem:
https://www.drupal.org/project/simplesamlphp_auth/issues/3349278

**Comment by tvdijen** [comment]
Already explained to you that the file was moved. Please use our mailing list if you don't understand this and not pollute the issue tracker.
