### ISSUE TITLE
Problem with typed static property 

### ISSUE THREAD

**Issue by amarc-sudo** [simplesamlphp/saml2#346]
After an update from symfony5/php7.4 to symfony6/php8.2 I get this error, I have no idea where it comes from.

request.CRITICAL: Uncaught PHP Exception Error: "Typed static property SimpleSAML\SAML2\Compat\ContainerSingleton::$container must not be accessed before initialization" at /var/www/html/project/vendor/simplesamlphp/saml2/src/SAML2/Compat/ContainerSingleton.php line 20 {"exception":"[object] (Error(code: 0): Typed static property SimpleSAML\\SAML2\\Compat\\ContainerSingleton::$container must not be accessed before initialization at /var/www/html/project/simplesamlphp/saml2/src/SAML2/Compat/ContainerSingleton.php:20)"}

**Comment by amarc-sudo** [comment]
Because of compatibility issues with symfony dependencies I had to use alpha versions, I use simplesamlphp/saml2 and simplesamlphp/simplesamlphp in dev version

If there's a way to solve the compatibility problems between stable and symfony 6.3, I'll take it.

**Comment by tvdijen** [comment]
Use the `release-2.1` branch of `simplesamlphp/simplesamlphp`.. It's soon to be officially released
