### ISSUE TITLE
unserialize error

### ISSUE THREAD

**Issue by estettler** [simplesamlphp/saml2#354]
I'm using 4.x with PHP 8.1.1 and suddenly I'm seeing this error:

`
Error: Cannot access property starting with "\0" in SAML2\XML\saml\NameIDType->__unserialize() (line 252 of /var/www/vendor/simplesamlphp/saml2/src/SAML2/XML/saml/NameIDType.php)`

Any idea how this might be debugged?

**Comment by tvdijen** [comment]
Hi! Try clearing your session storage. You are probably trying to unserialize a session that was serialized by an older version.

**Comment by estettler** [comment]
Thank you! That was it.
