### ISSUE TITLE
Missing SimpleSAML_Utilities

### ISSUE THREAD

**Issue by chriskl** [simplesamlphp/saml2#47]
Hi,

I'm trying to do some pretty basic IDP code ($class->receive()) and I get this:

```Fatal error: Class 'SimpleSAML_Utilities' not found in /vagrant/vendor/simplesamlphp/saml2/src/SAML2/Compat/Ssp/Container.php on line 39```

That's this:

```SimpleSAML_Utilities::debugMessage($message, $type);```

Far as I can tell the SimpleSAML_Utilities class simply does not exist.

**Comment by chriskl** [comment]
Ah - this isn't a bug is it - I need to implement the container?

**Comment by relaxnow** [comment]
Correct, sorry, for historical reasons we default to ssp.

**Comment by relaxnow** [comment]
Also from the [README](https://github.com/simplesamlphp/saml2/blob/master/README.md#before-you-use-it):
```
DO NOT USE THIS LIBRARY UNLESS YOU ARE INTIMATELY FAMILIAR WITH THE SAML2 SPECIFICATION.

If you are not familiar with the SAML2 specification and are simply looking to connect your application using SAML2, you should probably use SimpleSAMLphp.
```

If you're doing a simple IdP then you probably need [SimpleSAMLphp](https://simplesamlphp.org) proper.

**Comment by chriskl** [comment]
I know what I'm doing, just missed that detail...
