### ISSUE TITLE
SOAP backchannel assertion needs to be proxy-able

### ISSUE THREAD

**Issue by madmatt** [simplesamlphp/saml2#50]
Hi all,

For my current project, I need to relay the SOAP backchannel assertion via a Squid proxy, which isn't natively supported by the saml2 library.

Currently, I have made the following change in `src/SAML2/SOAPClient.php`. This options array is passed into the `new SOAPClient()` call.

```php
		$options = array(
			'uri' => $issuer,
			'location' => $msg->getDestination(),
			'stream_context' => $context,
			'proxy_host' => 'proxy-url.com',
			'proxy_port' => 8080,
		);
```

I want to submit this as a pull request, but aren't quite clear on the coupling. My proposal is to include new fields on the `SAML2_Message` object `$msg` that is passed into `SOAPClient::send()` for getting the proxyHost and proxyPort, and only set them in the `$options` array if they exist in the message.

That way, in `src/SAML2/HTTPArtifact.php` I can pull the required proxy options through the metadata retriever, and set them in the `SAML2_Message`. Then, I'd need to submit another pull request to the simplesamlphp/simplesamlphp project adding those variables to the `metadata-examples` folder for the `saml20-idp-remote.php` file.

Does this make sense, before I go ahead and make the changes? Because it requires interaction between two modules, I thought I'd outline my suggestion before making the change.

Thanks!

**Comment by thijskh** [comment]
Fixed with #51
