### ISSUE TITLE
FATAL ERROR! assert() ignores namespace in Assertion.php

### ISSUE THREAD

**Issue by Yurist-85** [simplesamlphp/saml2#62]
This code produces **FATAL ERROR**
```
585: assert('$key->type === XMLSecurityKey::RSA_SHA1');
```
It **MUST** be
```
585: assert('$key->type === RobRichards\XMLSecLibs\XMLSecurityKey::RSA_SHA1');
```

**Comment by thijskh** [comment]
Hi. This code did not have any unit tests, so I added some. They demonstrate that the assertion failure is not triggered in our use case. Can you show the code you use to call `validate()`?

**Comment by jaimeperez** [comment]
We need to stop using `assert()`, it's simply not working...

**Comment by thijskh** [comment]
What I said above is incorrect. The tests pass on my system, but fail on Travis on the same issue.

**Comment by thijskh** [comment]
Alright, it seems my PHP install took some coercion to get assertions to be actually triggered. The tests indeed reproduce the issue, which is now fixed. Agree with Jaime that in the long term, we should prefer typehints over assertions.
