### ISSUE TITLE
unable to set "NameQualifier" and "Format" attributes for saml:Issuer

### ISSUE THREAD

**Issue by manzolo** [simplesamlphp/saml2#67]
We are implementing a SAML2 SP to connect SAML2 to SPID (a sort of italian national sso). We encountered a major issue: SPID requires 
"NameQualifier" and "Format" attributes in the Issuer section like:
                 
`<saml:Issuer NameQualifier="..(string).." Format="..(string)..">
{issuer string value}
</saml:Issuer>`

but we cant set these parameters (optionals in standard specs).

    Line 432 (commit b21340c), file: ./saml2/src/SAML2/Message.php:
the code/configuration doesn't allow to add attributes to the saml:Issuer element but only the issuer value (string)

Thanks a lot for the support

**Comment by relaxnow** [comment]
You're right, we haven't used this apparently.

Though it looks easy to fix by introducing an ```Issuer``` class that is accepted by ```setIssuer``` as well as a string (for backwards compatibility) and used by ```toMessage()```.
With a unit test naturally.

What you you think @jaimeperez ?

**Comment by thijskh** [comment]
Both `NameID ` and `Issuer` are of type `NameIDtype` so probably we (c/s)hould share some code there.

**Comment by manzolo** [comment]
I think it's not only the toUnsignedXML function to be changed . If I understand the SAML2 operation must also change the Assertion.php class, SOAPClient.php class send function, the constructor of the Message.php class, but doing these changes many functional tests fail in my local branch...
