### ISSUE TITLE
Class 'XMLSecurityKey' not found in Assertion

### ISSUE THREAD

**Issue by ajmichels** [simplesamlphp/saml2#70]
An exception is being thrown when I attempt to process an assertion. `Class 'XMLSecurityKey' not found .../vendor/simplesamlphp/saml2/src/SAML2/Assertion.php(585) : assert code on line 1`

If I comment out `assert('$key->type === XMLSecurityKey::RSA_SHA1');` the exception goes away.

I am using simplesamlphp/saml2 v2.2 and PHP v5.4.45

**Comment by jaimeperez** [comment]
Thanks @ajmichels!
