### ISSUE TITLE
Undefined class constant 'NAME_NEW' in PrivateKeyLoader

### ISSUE THREAD

**Issue by ajmichels** [simplesamlphp/saml2#71]
`Undefined class constant 'NAME_NEW' in /Users/amichels/projects/caringbridge/xsaml/vendor/simplesamlphp/saml2/src/SAML2/Certificate/PrivateKeyLoader.php on line 49`

It looks like maybe PrivateKeyLoader line 49 should be using `PrivateKeyConfiguration::NAME_NEW` instead of `PrivateKey::NAME_NEW`.

With simplesamlphp/saml2 v2.2 on PHP 5.4.45

**Comment by jaimeperez** [comment]
Thanks for reporting this @ajmichels!
