### ISSUE TITLE
Call to a member function debug() on a non-object in NameIdDecryptionTransformer

### ISSUE THREAD

**Issue by ajmichels** [simplesamlphp/saml2#72]
`Call to a member function debug() on a non-object in /Users/amichels/projects/caringbridge/xsaml/vendor/simplesamlphp/saml2/src/SAML2/Assertion/Transformer/NameIdDecryptionTransformer.php on line 63`

It looks like you forgot to set `$this->logger = $logger` in the constructor for NameIdDecryptionTransformer.

Using simplesamlphp/saml2 v2.2 on PHP 5.4.45

**Comment by jaimeperez** [comment]
Thanks again!
