### ISSUE TITLE
SimpleSAML_Utilities class not found

### ISSUE THREAD

**Issue by macintoshplus** [simplesamlphp/saml2#86]
Hi,

I want use this library for add SAML2 capabilities at my IdP but I cannot `receive` the HTTPPost bindings.

```
( ! ) Fatal error: Class 'SimpleSAML_Utilities' not found in /src/vendor/simplesamlphp/saml2/src/SAML2/Compat/Ssp/Container.php on line 44
Call Stack
#	Time	Memory	Function	Location
1	0.0007	240896	{main}( )	.../ssosaml.php:0
2	0.1345	1170024	SAML2\HTTPPost->receive( )	.../ssosaml.php:18
3	0.1375	1197880	SAML2\Compat\Ssp\Container->debugMessage( )	.../HTTPPost.php:71
```

The `SimpleSAML_Utilities` is not an saml2 library component.

How to ?

Thanks in advance

**Comment by jaimeperez** [comment]
Hi,

The SAML2 library has a compatibility layer that requires either SimpleSAMLphp or your own implementation of some classes. Given that you are apparently implementing SSO by yourself, you may want to provide your own compatibility layer.

On the other hand, I would recommend you not to implement the SAML2 protocol on your own, as it is a complex thing to do and it's very easy to make mistakes that could lead to security issues if you don't know what you are doing. In that case, it's much easier to just use SimpleSAMLphp and forget about it.

**Comment by macintoshplus** [comment]
Thanks for the answer,
I don't want implement the SAML2 stack, I want use your library implementation for add this protocol into my existing IdP.
Now I use the `simplesamlphp` like a component.
