### ISSUE TITLE
Switch to using ass/xmlsecurity

### ISSUE THREAD

**Issue by relaxnow** [simplesamlphp/saml2#9]
Several forks of Rob Richards XML Security library were attempted, [the fork by Andreas Schamberger seems to be the one most far along](https://github.com/aschamberger/XmlSecurity).

Maybe we could switch?

**Comment by thijskh** [comment]
It seems that robrichards has been revived.

**Comment by jaimeperez** [comment]
Indeed! The XML canonicalization performance issue is now fixed upstream, I got some other cleanings of the code in, and I also just submitted a PR providing PSR-0 compatibility :smile:

**Comment by thijskh** [comment]
Invite him to the next hackathon?
