### ISSUE TITLE
sspmod_saml_Message class usage in HTTPArtifact.php

### ISSUE THREAD

**Issue by marcimat** [simplesamlphp/saml2#92]
Not sure but the use of sspmod_saml_Message class into https://github.com/simplesamlphp/saml2/blob/master/src/SAML2/HTTPArtifact.php#L122 will search for a "SAML2\sspmod_saml_Message" class, since 431576a6f104b6 certainly. Isn't `\sspmod_saml_Message` to use there ?
```diff
- sspmod_saml_Message::addSign($this->spMetadata, $idpMetadata, $ar); // Shoaib - moved from the SOAPClient.
+ \sspmod_saml_Message::addSign($this->spMetadata, $idpMetadata, $ar); // Shoaib - moved from the SOAPClient.
```

**Comment by thijskh** [comment]
Yes, agreed. Fixed in 846cbadff2eafbf45780ec4f0955d53afa6ead69. Thanks!

Unfortunately this code is only usable with simpleSAMLphp so the testsuite does not quite cover it.
