### ISSUE TITLE
Symfony SAML Bridge Bundle: AdactiveSAS/saml2-bridge-bundle 

### ISSUE THREAD

**Issue by moroine** [simplesamlphp/saml2#93]
Hi,

First of all I would like to thank you for that library !

I was looking creating an identity provider on a Symfony application. As I didn't found anything relevant, I decided to create one.

If you're interested about my changes you could take a look at https://github.com/AdactiveSAS/saml2-bridge-bundle.

The fact is that I'm new with SAML although I read the whole specification. So I'm trying make some noise in order to attract some people interested to help us evolved that project.

Anyway I would be happy to discuss with you about it.

**Comment by thijskh** [comment]
Thanks for the information. Since this is not an action item I'll close the ticket.
