### ISSUE TITLE
PHP 7.1 support and xmlseclibs

### ISSUE THREAD

**Issue by chris1312** [simplesamlphp/saml2#97]
`simplesamlphp/saml2` depends on `robrichards/xmlseclibs` and it is using mcrypt_* functions. Therefore, using this library it results into deprecated errors.

Why using Mcrypt is wrong? Read here https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong

Has anybody tested SAML2 with `robrichards/xmlseclibs` 3.0.0+?

**Comment by tvdijen** [comment]
It's only a couple of days old.....  Have you tested it for yourself?

**Comment by thijskh** [comment]
Yes, I've done some testing with simpleSAMLphp and OpenConext-engineblock and their core functionality remains working, also their testsuites pass with this upgrade. We need to keep it at 2.0 or 3.0 as saml2 currently still supports PHP < 5.6.

**Comment by chris1312** [comment]
That's nice to hear. Thanks for the update!
