### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by levelfivehub** [simplesamlphp/saml2#99]
Dear all,

When will the next release be made so I can make use of the XMLSecLibs V3.0.0?  This is required for php 7.1 support.  It is quite urgent and I do not want to use master as a branch for release.

**Comment by thijskh** [comment]
We will likely tag a new release in the near future. However I don't share your sense of urgency since mcrypt is only deprecated in php 7.1 so will work just fine.

**Comment by levelfivehub** [comment]
Hi,

7.1 is exactly what I am on.  Is there any prediction on when a new release will be made for 7.1?

**Comment by thijskh** [comment]
Mcrypt is only deprecated in 7.1. So mcrypt will work fine with PHP 7.1.

**Comment by thijskh** [comment]
v3.0.0 is now released.
